testname: webMUSHRA Decoder Listening Test
testId: Ambisonic_Decoder_Test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: >
        Welcome to the Ambisonic Decoder Listening Test <br/>
        There are halves to this test. Part 1 is based on tracks containing sound source characteristics <br/>
        while part 2 will be based around more environmental characteristics. <br/>
        Once all tests are finished, please fill ot the questinonnaire and submit the results <br/>
        You may take a break or pull out from doing the test at any moment <br/>
        Thank you! <br/>
        
    - type: generic
      id: Instructions
      name: Instructions
      content: > 
        This is the first half of the test. This half will test three different characteristics; <br/>
        Localisation accuracy, Localisation and Apparent Source width <br/> <br/>
        For each characteristic there will be an available reference on the left hand side of the page which you can listen to at any time. <br/>
        There will be a number of audio files for you to listen to which must be rated from 0-100 using the associated sliders. <br/>
        This rating should be based on how similar the selected audio file is to the reference file for the given characteristic. <br/>
        A rating of 0 would describe the chosen file as pure noise and a rating of 100 would state the file has no difference to the available reference. <br/> <br/>
        Please ensure to compare the selected track against the REFERENCE ONLY and not to the other audio files. <br/> <br/>
        There are also two sliders under the waveform of the audio file. <br/>
        These can be dragged at any time to listen to certain points of the audio file in a looped fashion. <br/>
        
        
    - type: mushra
      id: CubeAccHorSpk
      name: HORIZONTAL LOCALISATION ACCURACY; CUBE LAYOUT, AT SPEAKER
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Horiz_Cube/At_Speaker/locAcc_cube_speaker_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Horiz_Cube/At_Speaker/locAcc_cube_allRad_speaker.wav 
          C2: configs/resources/audio/LocAcc_Horiz_Cube/At_Speaker/locAcc_cube_DTS_speaker.wav 
          C3: configs/resources/audio/LocAcc_Horiz_Cube/At_Speaker/locAcc_cube_Harpex_speaker.wav
    - type: mushra
      id: CubeAccHorBet
      name: HORIZONTAL LOCALISATION ACCURACY; CUBE LAYOUT, BETWEEN SPEAKERS
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Horiz_Cube/Between_Speaker/locAcc_cube_between_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Horiz_Cube/Between_Speaker/locAcc_cube_allRad_between.wav 
          C2: configs/resources/audio/LocAcc_Horiz_Cube/Between_Speaker/locAcc_cube_DTS_between.wav 
          C3: configs/resources/audio/LocAcc_Horiz_Cube/Between_Speaker/locAcc_cube_Harpex_between.wav
    - type: mushra
      id: CubeAccElevSpk
      name: ELEVATIONAL LOCALISATION ACCURACY; CUBE LAYOUT, AT SPEAKER
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Elev_Cube/At_Speaker/locAcc_cube_speaker_elev_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Elev_Cube/At_Speaker/locAcc_cube_allRad_speaker_elev.wav 
          C2: configs/resources/audio/LocAcc_Elev_Cube/At_Speaker/locAcc_cube_Harpex_speaker_elev.wav 
          C3: configs/resources/audio/LocAcc_Elev_Cube/At_Speaker/locAcc_cube_DTS_speaker_elev.wav
    - type: mushra
      id: CubeAccElevBet
      name: ELEVATIONAL LOCALISATION ACCURACY; CUBE LAYOUT, BETWEEN SPEAKERS
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Elev_Cube/Between_Speakers/locAcc_cube_between_elev_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Elev_Cube/Between_Speakers/locAcc_cube_allRad_between_elev.wav 
          C2: configs/resources/audio/LocAcc_Elev_Cube/Between_Speakers/locAcc_cube_Harpex_between_elev.wav 
          C3: configs/resources/audio/LocAcc_Elev_Cube/Between_Speakers/locAcc_cube_DTS_between_elev.wav
    - type: mushra
      id: CinemaAccHorSpk
      name: HORIZONTAL LOCALISATION ACCURACY; 7.1.4 LAYOUT, AT SPEAKER
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Horiz_7.1.4/At_Speaker/7.1.4_speaker_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Horiz_7.1.4/At_Speaker/7.1.4_AllRad_speaker.wav 
          C2: configs/resources/audio/LocAcc_Horiz_7.1.4/At_Speaker/7.1.4_Harpex_speaker.wav 
          C3: configs/resources/audio/LocAcc_Horiz_7.1.4/At_Speaker/7.1.4_DTS_speaker.wav
    - type: mushra
      id: CinemaAccHorBet
      name: HORIZONTAL LOCALISATION ACCURACY; 7.1.4 LAYOUT, BETWEEN SPEAKERS
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Horiz_7.1.4/Between_Speakers/7.1.4_between_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Horiz_7.1.4/Between_Speakers/7.1.4_AllRad_between.wav 
          C2: configs/resources/audio/LocAcc_Horiz_7.1.4/Between_Speakers/7.1.4_Harpex_between.wav 
          C3: configs/resources/audio/LocAcc_Horiz_7.1.4/Between_Speakers/7.1.4_DTS_between.wav
    - type: mushra
      id: CinemaAccElevSpk
      name: ELEVATIONAL LOCALISATION ACCURACY; 7.1.4 LAYOUT, AT SPEAKER
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Elev_7.1.4/At_Speaker/7.1.4_speaker_elev_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Elev_7.1.4/At_Speaker/7.1.4_AllRad_speaker_elev.wav 
          C2: configs/resources/audio/LocAcc_Elev_7.1.4/At_Speaker/7.1.4_Harpex_speaker_elev.wav 
          C3: configs/resources/audio/LocAcc_Elev_7.1.4/At_Speaker/7.1.4_DTS_Speaker_elev.wav
    - type: mushra
      id: CinemaAccElevBet
      name: ELEVATIONAL LOCALISATION ACCURACY; 7.1.4 LAYOUT, BETWEEN SPEAKERS
      content: Please rate the test files from 0-100 on how similar the horizontal position of the sound source is to the available reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/LocAcc_Elev_7.1.4/Between_Speakers/7.1.4_between_elev_ref.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LocAcc_Elev_7.1.4/Between_Speakers/7.1.4_AllRad_between_elev.wav 
          C2: configs/resources/audio/LocAcc_Elev_7.1.4/Between_Speakers/7.1.4_Harpex_between_elev.wav 
          C3: configs/resources/audio/LocAcc_Elev_7.1.4/Between_Speakers/7.1.4_DTS_between_elev.wav
    - type: mushra
      id: localiseCloseCube
      name: CLOSE PROXIMITY SOURCE LOCALISATION; CUBE LAYOUT
      content: Please rate the test files from 0-100 on how similar the positions of both sound sources are to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Localisation_Cube/Close/localisation_close_ref.wav
      createAnchor35: true
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Localisation_Cube/Close/localisation_AllRad_close.wav
          C2: configs/resources/audio/Localisation_Cube/Close/localisation_Harpex_close.wav
          C3: configs/resources/audio/Localisation_Cube/Close/localisation_DTS_close.wav
    - type: mushra
      id: localiseOppCube
      name: CLOSE PROXIMITY SOURCE LOCALISATION; 7.1.4 LAYOUT
      content: Please rate the test files from 0-100 on how similar the positions of both sound sources are to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Localisation_7.1.4/Close/localisation_close_ref.wav
      createAnchor35: true
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Localisation_7.1.4/Close/localisation_AllRad_close.wav
          C2: configs/resources/audio/Localisation_7.1.4/Close/localisation_Harpex_close.wav
          C3: configs/resources/audio/Localisation_7.1.4/Close/localisation_DTS_close.wav
    - type: mushra
      id: localiseCloseCinema
      name: DIAMETRICALLY OPPOSITE SOURCE LOCALISATION; CUBE LAYOUT
      content: Please rate the test files from 0-100 on how similar the positions of both sound sources are to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Localisation_Cube/Opposite/localisation_opposite_ref.wav
      createAnchor35: true
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Localisation_Cube/Opposite/localisation_AllRad_opposite.wav
          C2: configs/resources/audio/Localisation_Cube/Opposite/localisation_Harpex_opposite.wav
          C3: configs/resources/audio/Localisation_Cube/Opposite/localisation_DTS_opposite.wav        
    - type: mushra
      id: localiseOppCinema
      name: DIAMETRICALLY OPPOSITE SOURCE LOCALISATION; 7.1.4 LAYOUT
      content: Please rate the test files from 0-100 on how similar the positions of both sound sources are to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Localisation_7.1.4/Opposite/localisation_opposite_ref.wav
      createAnchor35: true
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Localisation_7.1.4/Opposite/localisation_AllRad_opposite.wav
          C2: configs/resources/audio/Localisation_7.1.4/Opposite/localisation_Harpex_opposite.wav
          C3: configs/resources/audio/Localisation_7.1.4/Opposite/localisation_DTS_opposite.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: false
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 20
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
          - type: likert
            name: experience
            label: Listening Test Experience
            response:
             - value: none
               label: None
             - value: little
               label: Little (1 or 2 previous tests)
             - value: extensive
               label: Considerable (Many Tests, Trained Listener)
          - type: likert
            name: detail
            label: Do you work with Audio professionally? If so, for how long?
            response: 
             - value: none
               label: 0 years
             - value: little
               label: 1-3 years
             - value: intermed
               label: 3-5 years
             - value: extensive
               label: 5+ years